# /common_playbook/roles/gitlab/tasks

- name: "install the latest version of curl, policycoreutils, openssh-server, openssh-clients"
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - policycoreutils
    - openssh-server
    - openssh-clients

- name: "start service sshd, if not running"
  service: name=sshd state=started enabled=yes

- name: "download the gitlab installation script"
  get_url: dest=/tmp force=yes timeout={{ get_url_timeout }} url="{{ gitlab.url }}{{ gitlab.script }}"

- name: "execute gitlab installation script"
  command: "sh /tmp/{{ gitlab.script }}"

# GitLab Community Editionのインストール
- name: "install the latest version of gitlab-ce"
  yum: name=gitlab-ce state=latest
  notify:
    - configure and start gitlab

# external_urlと設定値の間に"="は不要
- name: "edit external_url in {{ gitlab.conf }}"
  replace: dest="{{ gitlab.conf }}" regexp='^external_url.*$' replace="external_url \"http://{{ ansible_default_ipv4.address }}/gitlab\"" backup=yes
  notify:
    - configure and start gitlab

- name: "edit nginx listen port in {{ gitlab.conf }}"
  replace: dest="{{ gitlab.conf }}" regexp='.*nginx\[\'listen_port\'\].*$' replace="nginx['listen_port'] = {{ gitlab.nginx_port }}" backup=yes
  notify:
    - configure and start gitlab

- name: "edit nginx listen port in {{ gitlab.conf }}"
  replace: dest="{{ gitlab.conf }}" regexp='.*unicorn\[\'port\'\].*$' replace="unicorn['port'] = {{ gitlab.unicorn_port }}" backup=yes
  notify:
    - configure and start gitlab

- name: "edit nginx listen port in {{ gitlab.erb }}"
  replace: dest="{{ gitlab.erb }}" regexp='.*unicorn\[\'port\'\].*$' replace="unicorn['port'] = {{ gitlab.unicorn_port }}" backup=yes

- name: "put {{ gitlab.httpd_conf }}"
  template: src=gitlab.conf.j2 dest="{{ gitlab.httpd_conf }}"
  notify:
    - restart httpd

- name: "start service httpd, if not running"
  service: name=httpd state=started enabled=yes