# /common_playbook/roles/zabbix/defaults

version:
  zabbix: 5.4.1
  zabbix_major: 5.4
zabbix:
  source_url: https://cdn.zabbix.com/zabbix/sources/stable/{{ version.zabbix_major }}/zabbix-{{ version.zabbix }}.tar.gz
  conf: /usr/local/etc/zabbix_server.conf
  log_dir: /var/log/zabbix
  dir: /var/www/html/zabbix
  user: zabbix
  mariadb_name: zabbix
  mariadb_user: zabbix
  mariadb_pass: zabbix
  start_snmptrapper: 1
  start_pollers: 10
  start_db_syncers: 4
  cache_size: 32M