# /common_playbook/roles/gitlab/defaults

gitlab:
  url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/
  script: script.rpm.sh
  conf: /etc/gitlab/gitlab.rb
  erb: /opt/gitlab/embedded/cookbooks/gitlab/templates/default/gitlab.yml.erb
  httpd_conf: /etc/httpd/conf.d/gitlab.conf
  unicorn_port: 8888
  nginx_port: 10080