# /common_playbook/roles/zabbix-agent/tasks

# ATTENTION ########################
# 以下の値は、各プロジェクトごとに指定すること
# 
# {{ version.zabbix_agent }}
# {{ zabbix.server }}
####################################

- name: "add zabbix repository"
  yum_repository: name=zabbix description=zabbix baseurl="{{ zabbix.repo_url }}" gpgkey="{{ zabbix.repo_key }}" gpgcheck={{ gpgcheck }} enabled=no

# GPG KEYチェックなし
- name: "install the latest version of zabbix-agent"
  dnf: name=zabbix-agent state=latest disable_gpg_check=yes enablerepo=zabbix

# 接続するZabbixサーバのアドレスを指定
- name: "edit Server of {{ zabbix.agentd_conf }}"
  replace: path="{{ zabbix.agentd_conf }}" regexp='^Server=.*$' replace="Server={{ zabbix.server }}" backup=yes

- name: "edit ServerActive of {{ zabbix.agentd_conf }}"
  replace: path="{{ zabbix.agentd_conf }}" regexp='^ServerActive=.*$' replace="ServerActive={{ zabbix.server }}" backup=yes

- name: "edit Hostname of {{zabbix.agentd_conf}}"
  replace: path="{{ zabbix.agentd_conf }}" regexp='^Hostname=.*$' replace="Hostname={{ ansible_hostname }}" backup=yes

- name: "start service zabbix-agent, if not running"
  service: name=zabbix-agent state=started enabled=yes