# /common_playbook/roles/elasticsearch/handlers

- name: restart httpd
  service: name=httpd state=restarted
  when: not httpd.compile_from_src

- name: restart apachectl daemon
  command: "{{ httpd.ctlbin }} graceful"
  when: httpd.compile_from_src

- name: restart kibana
  service: name=kibana state=restarted