# /common_playbook/roles/sox/tasks

- name: "add epel repository"
  yum_repository: name=epel description=epel baseurl="{{ epel_repo }}" enabled=no

# スクリプト実行に必要なパッケージ
- name: "install the latest version of usbutils, alsa-lib-devel, alsa-utils, gcc-c++, libmad, libmad-devel, libid3tag, libid3tag-devel, lame, lame-devel, flac-devel, libvorbis-devel"
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - gcc-c++
    - libid3tag
    - libid3tag-devel
    - flac-devel
    - libvorbis-devel

- name: "download the sox source files"
  get_url: dest=/tmp force=yes timeout={{ get_url_timeout }} url="{{ sox.source_url }}"

- name: "unpacks the sox source files"
  unarchive: remote_src=yes src=/tmp/sox-{{ sox.version }}.tar.gz dest=/usr/local/src

- name: "configure the sox programs"
  command: chdir=/usr/local/src/sox-{{ sox.version }} ./configure

- name: "make the sox programs"
  command: make -s chdir=/usr/local/src/sox-{{ sox.version }}

- name: "install the sox programs"
  command: make install chdir=/usr/local/src/sox-{{ sox.version }}