# /common_playbook/roles/php-mongodb/tasks

# ATTENTION ########################
# 以下の値は、各プロジェクトごとに指定すること
# 
# {{ httpd.compile_from_src }}
#
####################################

- name: "delete the mongodb library source files"
  file: path=/tmp/mongo-php-driver state=absent

- name: "git checkout the mongodb library source files"
  git: dest=/tmp/mongo-php-driver repo="{{ php_mongo.repo }}"

- name: "phpize the mongodb library"
  command: "chdir=/tmp/mongo-php-driver phpize"

- name: "configure the mongodb library"
  command: chdir=/tmp/mongo-php-driver ./configure

- name: "make the mongodb library"
  make: chdir=/tmp/mongo-php-driver

- name: "install the mongodb library"
  make: chdir=/tmp/mongo-php-driver target=install

- name: "add a block to {{ php.ini }} if it does not exist"
  blockinfile:
    dest: "{{ php.ini }}"
    marker: "; {mark} ANSIBLE MANAGED BLOCK (MONGODB)"
    backup: yes
    block: |
       extension=mongodb.so
  notify:
    - restart httpd
    - restart apachectl daemon