# /common_playbook/roles/php-mongodb/tasks

# ATTENTION ########################
# 以下の値は、各プロジェクトごとに指定すること
# 
# {{ httpd.compile_from_src }}
# {{ php.phpize }}
# {{ php.php-config }}
#
####################################

- name: "add epel repository"
  yum_repository: name=epel description=epel baseurl="{{ epel_repo }}" gpgkey="{{ epel_key }}" gpgcheck={{ gpgcheck }} enabled=no
  when: ansible_architecture is not match("^arm")

- name: "add epel repository"
  yum_repository: name=epel description=epel baseurl="{{ epel_repo_arm }}" gpgcheck=no enabled=no
  when: ansible_architecture is match("^arm")

- name: "install the latest version of re2c"
  yum: name=re2c state=latest enablerepo=epel

- name: "delete the mongodb library source files"
  file: path="{{ php_mongo.basedir }}" state=absent

- name: "git checkout the mongodb library source files"
  git: dest="{{ php_mongo.basedir }}" repo="{{ php_mongo.repo }}"

- name: "phpize the mongodb library"
  command: "chdir={{ php_mongo.basedir }} {{ php.phpize }}"

- name: "configure the mongodb library"
  command: "chdir={{ php_mongo.basedir }} ./configure --with-php-config={{ php.php_config }}"

- name: "make the mongodb library"
  make: "chdir={{ php_mongo.basedir }}"

- name: "install the mongodb library"
  make: "chdir={{ php_mongo.basedir }} target=install"
  
- name: "copy mongodb.so library to {{ php.extensiondir }}"
  copy: src="{{ php_mongo.basedir }}/modules/mongodb.so" remote_src=yes dest="{{ php.extensiondir }}/mongodb.so" mode=0777

- name: "add a block to {{ php.ini }} if it does not exist"
  blockinfile:
    path: "{{ php.ini }}"
    marker: "; {mark} ANSIBLE MANAGED BLOCK (MONGODB)"
    backup: yes
    block: |
       extension=mongodb.so
  notify:
    - restart httpd
    - restart apachectl daemon