# /common_playbook/roles/jenkins/tasks

# ATTENTION ########################
# 以下の値は、各プロジェクトごとに指定すること
# 
# {{ httpd.compile_from_src }}
# {{ httpd.jenkins_conf }}
#
####################################

- name: "install the latest version of java-{{ jdk_ver }}-openjdk, httpd"
  dnf: name={{ packages }} state=latest
  vars:
    packages:
      - java-{{ jdk_ver }}-openjdk
      - httpd

- name: "add jenkins repository"
  yum_repository: name=jenkins description=jenkins baseurl="{{ jenkins.repo_url }}" gpgkey="{{ jenkins.repo_key }}" gpgcheck={{ gpgcheck }} enabled=no

- name: "install the latest version of jenkins"
  dnf: name=jenkins state=latest enablerepo=jenkins

- name: "edit JENKINS_ARGS in {{ jenkins.conf }}"
  replace: path="{{ jenkins.conf }}" regexp='.*JENKINS_ARGS.*=.*$' replace="JENKINS_ARGS="--prefix=/jenkins"" backup=yes

- name: "put {{ httpd.jenkins_conf }}"
  template: src=jenkins.conf.j2 dest="{{ httpd.jenkins_conf }}"
  notify:
    - restart httpd
    - restart apachectl daemon

- name: "add a block to {{ httpd.conf }} if it does not exist"
  blockinfile:
    path: "{{ httpd.conf }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (JENKINS)"
    backup: yes
    block: |
       Include {{ httpd.jenkins_conf }}
  notify:
    - restart apachectl daemon
  when: httpd.compile_from_src

# sudoの実行を可能にする
# パーミッションは440にする必要がある
- name: "add a sudoers file if it does not exist"
  copy: src=jenkins dest={{  jenkins.sudoers  }} owner=root group=root mode=0440

- name: "start service jenkins, if not running"
  service: name=jenkins state=started enabled=yes

- name: "start service httpd, if not running"
  service: name=httpd state=started enabled=yes