# /common_playbook/roles/jenkins/tasks

- name: "install the latest version of java-{{ jdk_ver }}-openjdk, httpd"
  yum: name={{ item }} state=latest
  with_items:
    - java-{{ jdk_ver }}-openjdk
    - httpd

- name: "download the jenkins repo file"
  get_url: dest=/etc/yum.repos.d/ force=yes timeout={{  get_url_timeout  }} url="{{  jenkins.url  }}"

- name: "import a rpm key from a url"
  rpm_key: state=present key="{{  jenkins.repokey  }}"

- name: "install the latest version of jenkins"
  yum: name=jenkins state=latest
  notify:
    - restart jenkins

- name: "edit JENKINS_ARGS in {{  jenkins.conf  }}"
  replace: dest="{{  jenkins.conf  }}" regexp='.*JENKINS_ARGS.*=.*$' replace="JENKINS_ARGS="--prefix=/jenkins"" backup=yes
  notify:
    - restart jenkins

- name: "put {{  jenkins.httpd_conf  }}"
  template: src=jenkins.conf.j2 dest="{{  jenkins.httpd_conf  }}"
  notify:
    - restart httpd

# sudoの実行を可能にする
- name: "add a sudoers file if it does not exist"
  copy: src=jenkins dest={{  jenkins.sudoers  }} owner=root group=root mode=0400

- name: "start service jenkins, if not running"
  service: name=jenkins state=started enabled=yes

- name: "start service httpd, if not running"
  service: name=httpd state=started enabled=yes