# /common_playbook/roles/jenkins/tasks

# ATTENTION ########################
# 以下の値は、各プロジェクトごとに指定すること
# 
# {{ httpd.compile_from_src }}
# {{ httpd.jenkins_conf }}
#
####################################

- name: "install the latest version of java-{{ jdk_ver }}-openjdk, httpd"
  yum: name={{ item }} state=latest
  with_items:
    - java-{{ jdk_ver }}-openjdk
    - httpd

- name: "download the jenkins repo file"
  get_url: dest=/etc/yum.repos.d/ force=yes timeout={{  get_url_timeout  }} url="{{  jenkins.url  }}"

- name: "import a rpm key from a url"
  rpm_key: state=present key="{{  jenkins.repokey  }}"

- name: "install the latest version of jenkins"
  yum: name=jenkins state=latest
  notify:
    - restart jenkins

- name: "edit JENKINS_ARGS in {{ jenkins.conf }}"
  replace: dest="{{ jenkins.conf }}" regexp='.*JENKINS_ARGS.*=.*$' replace="JENKINS_ARGS="--prefix=/jenkins"" backup=yes
  notify:
    - restart jenkins

- name: "put {{ httpd.jenkins_conf }}"
  template: src=jenkins.conf.j2 dest="{{ httpd.jenkins_conf }}"
  notify:
    - restart httpd
    - restart apachectl daemon

- name: "add a block to {{ httpd.conf }} if it does not exist"
  blockinfile:
    dest: "{{ httpd.conf }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (JENKINS)"
    backup: yes
    block: |
       Include {{ httpd.jenkins_conf }}
  notify:
    - restart apachectl daemon
  when: httpd.compile_from_src

# sudoの実行を可能にする
- name: "add a sudoers file if it does not exist"
  copy: src=jenkins dest={{  jenkins.sudoers  }} owner=root group=root mode=0400

- name: "start service jenkins, if not running"
  service: name=jenkins state=started enabled=yes

- name: "start service httpd, if not running"
  service: name=httpd state=started enabled=yes