# /common_playbook/roles/rsyncd/tasks

# ATTENTION ########################
# 以下の値は、各プロジェクトごとに指定すること
# 
# {{sync.user}}
# {{sync.group}}
# {{sync.module_name}}
# {{sync.allow_hosts}}
# {{sync.dest_path}}
#
####################################

- name: "put {{ rsyncd.conf }}"
  template: src=rsyncd.conf.j2 dest="{{ rsyncd.conf }}" owner=root group=root mode=0600
  notify: restart rsyncd

- name: "start service rsyncd, if not running"
  service: name=rsyncd state=started enabled=yes

# ログローテート
- name: "install the latest version of logrotate"
  yum: name=logrotate state=latest

# パーミッション644を指定しないとエラーで実行されない
- name: "add a {{ rsyncd.logrotate }} if it does not exist"
  copy: src=rsyncd dest={{ rsyncd.logrotate }} owner=root group=root mode=0644