# /common_playbook/roles/mariadb-for-zabbix/tasks

# ATTENTION ########################
# 以下の値は、各プロジェクトごとに指定すること
# 
# {{ version.mariadb }}
#
####################################

- name: "add mariadb repository"
  yum_repository: name=mariadb description=mariadb baseurl="{{ mariadb.repo_url }}" gpgkey="{{ mariadb.repo_key }}" gpgcheck={{ gpgcheck }} enabled=no
  when: ansible_architecture is not match("^arm")

- name: "add mariadb repository"
  yum_repository: name=mariadb description=mariadb baseurl="{{ mariadb.repo_url_arm }}" gpgkey="{{ mariadb.repo_key }}" gpgcheck={{ gpgcheck }} enabled=no
  when: ansible_architecture is match("^arm")

# mariadbの使用に必要なパッケージ
# ansibleのmysql_dbを使用する際はMySQL-pythonパッケージが必要
- name: "install the latest version of mariadb, mariadb-server, mariadb-devel, MySQL-python"
  yum: name={{ packages }} state=latest
  vars:
    packages:
      - mariadb
      - mariadb-server
      - mariadb-devel
      - MySQL-python

- name: "add a block to {{ mariadb.srv_conf }} if it does not exist"
  blockinfile:
    path: "{{ mariadb.srv_conf }}"
    backup: yes
    insertafter: '\[mysqld\]'
    block: |
       character-set-server = utf8
       collation-server     = utf8_bin
       skip-character-set-client-handshake
       innodb_file_per_table
  notify:
    - restart mariadb

- name: "start service mariadb, if not running"
  service: name=mariadb state=started enabled=yes

- name: "show full status of mariadb"
  command: "mysql -V"
  register: mariadb_status
  changed_when: false

- name: "debug full status of mariadb"
  debug: var=mariadb_status.stdout_lines
  when: mariadb_status is succeeded