# /zabbix/roles/snmptt/tasks

# ATTENTION ########################
# 以下の値は、各プロジェクトごとに指定すること
# 
# {{ snmp.vendormibs }}
# {{ zabbix.conf }}
# {{ zabbix.snmptrapper }}
#
####################################

- name: "add epel repository"
  yum_repository: name=epel description=epel baseurl="{{ epel_repo }}" gpgkey="{{ epel_key }}" gpgcheck={{ gpgcheck }} enabled=no

# SNMPTTのインストールに必要なパッケージ
- name: "install the latest version of net-snmp-utils, net-snmp-perl, perl-Sys-Syslog, perl(SNMP), perl(XML::Simple)"
  yum: name={{ item }} state=latest
  with_items:
    - net-snmp-utils
    - net-snmp-perl
    - perl-Sys-Syslog
    - perl(SNMP)
    - perl(XML::Simple)

- name: "install the latest version of snmptt"
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - snmptt

# 全てのTrapデータをSNMPTTに転送
- name: "add a block to {{ snmptrapd.conf }} file if it does not exist"
  blockinfile:
    dest: "{{ snmptrapd.conf }}"
    backup: yes
    block: |
       disableAuthorization yes
       traphandle default /usr/sbin/snmptthandler
  notify:
    - restart snmptrapd

# snmptrapdの起動オプションを変更
#
# -m +ALL	全てのMIBをロードする
# -Lsd		SyslogにLOG_DAEMONファシリィティで書き込み
# -On		OIDを名称に変更しない（SNMPTTが行う）
# -p		PIDファイルの指定
# -M		読み込むMIBファイルがあるディレクトリ
- name: "add a block to {{ snmptrapd.script }} if it does not exist"
  blockinfile:
    dest: "{{ snmptrapd.script }}"
    backup: yes
    block: |
       OPTIONS="-m +ALL -Lsd -On -p /var/run/snmptrapd.pid -M /usr/share/snmp/mibs:{{ snmp.vendormibs }}"
  notify:
    - restart snmptrapd

# SNMP Handler経由の場合はdaemonを指定
- name: "edit mode of {{ snmptt.ini }}"
  replace: dest="{{ snmptt.ini }}" regexp='mode = .*$' replace="mode = daemon" backup=yes
  notify:
    - restart snmptt

# NetSNMPでPerlモジュールを使用する
- name: "edit net_snmp_perl_enable of {{ snmptt.ini }}"
  replace: dest="{{ snmptt.ini }}" regexp='net_snmp_perl_enable = .*$' replace="net_snmp_perl_enable = 1" backup=yes
  notify:
    - restart snmptt

- name: "edit net_snmp_perl_best_guess of {{ snmptt.ini }}"
  replace: dest="{{ snmptt.ini }}" regexp='net_snmp_perl_best_guess = .*$' replace="net_snmp_perl_best_guess = 2" backup=yes
  notify:
    - restart snmptt

# Syslogへは、snmptrapdがログ書き込みを行う
- name: "edit syslog_enable of {{ snmptt.ini }}"
  replace: dest="{{ snmptt.ini }}" regexp='syslog_enable = .*$' replace="syslog_enable = 0" backup=yes
  notify:
    - restart snmptt

# 日付フォーマットを指定
- name: "edit date_time_format of {{ snmptt.ini }}"
  replace: dest="{{ snmptt.ini }}" regexp='.*date_time_format =.*$' replace="date_time_format = %H:%M:%S %Y/%m/%d" backup=yes
  notify:
    - restart snmptt

# snmptt.log上の[ZBXTRAP] [IPアドレス]が記された行のみZabbixサーバに取り込まれる
- name: "add a {{ snmptt.conf }} file if it does not exist"
  copy: src=snmptt.conf dest={{ snmptt.conf }} owner=root group=root mode=0644
  notify:
    - restart snmptt

# サービス起動
- name: "start service snmptrapd, if not running"
  service: name=snmptrapd state=started enabled=yes

- name: "start service snmptt, if not running"
  service: name=snmptt state=started enabled=yes

- name: "add a block to {{ zabbix.conf }} if it does not exist"
  blockinfile:
    dest: "{{ zabbix.conf }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (SNMPTT)"
    backup: yes
    block: |
       SNMPTrapperFile=/var/log/snmptt/snmptt.log
       StartSNMPTrapper={{ zabbix.start_snmptrapper }}