# /common_playbook/roles/setup/tasks

# Amazon Linuxの判定
- name: "change ansible_distribution_major_version at Amazon Linux"
  set_fact: ansible_distribution_major_version=6
  when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'upstart'

- name: "change ansible_distribution_major_version at Amazon Linux2"
  set_fact: ansible_distribution_major_version=7
  when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'systemd'

# CentOS7では初期状態では実行権限が付与されていない
- name: "add mode the /etc/rc.d/rc.local file executable"
  file: path=/etc/rc.d/rc.local mode="u+x"

# @Development toolsはstate=presentを指定
- name: "install the latest version of @Development tools"
  dnf: name="@Development tools" state=present

- name: "add epel repository"
  yum_repository: name=epel description=epel baseurl="{{ epel_repo }}" gpgkey="{{ epel_key }}" gpgcheck={{ gpgcheck }} enabled=no
  when: ansible_architecture is not match("^arm") and not ansible_distribution_major_version == "8"

- name: "add epel repository"
  yum_repository: name=epel description=epel metalink="{{ epel_metalink }}" gpgkey="{{ epel_key }}" gpgcheck={{ gpgcheck }} enabled=no
  when: ansible_architecture is not match("^arm") and ansible_distribution_major_version == "8"

- name: "add epel repository"
  yum_repository: name=epel description=epel baseurl="{{ epel_repo_arm }}" gpgcheck=no enabled=no
  when: ansible_architecture is match("^arm")

- name: "install the latest version of wget, ntpdate, libselinux-python, git, python-pip"
  dnf: name={{ packages }} state=latest enablerepo=epel
  vars:
    packages:
      - wget
      - ntpdate
      - libselinux-python
      - git
      - python-pip
  when: not ansible_distribution_major_version == "8"

- name: "install the latest version of wget, git"
  dnf: name={{ packages }} state=latest enablerepo=epel
  vars:
    packages:
      - wget
      - git
  when: ansible_distribution_major_version == "8"

# expactモジュールの利用に必要
- name: "install pexpect package"
  pip: name=pexpect

- name: "stop service iptables"
  service: name={{ item }} enabled=no state=stopped
  with_items:
    - iptables
    - ip6tables
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- name: "stop service firewalld"
  service: name=firewalld enabled=no state=stopped
  when: ansible_distribution == "CentOS" and not ansible_distribution_major_version == "6"

- name: "retrieve selinux config"
  stat: path=/etc/selinux/config
  register: selinux_conf

# historyコマンドに時刻情報を付加する
- name: "add a block to /etc/bashrc if it does not exist"
  blockinfile:
    path: /etc/bashrc
    backup: yes
    block: |
      HISTSIZE=50000
      HISTTIMEFORMAT='%F %T '

# libselinux-pythonパッケージのインストールが必要
- name: "disable SELinux"
  selinux: state=disabled
  when: selinux_conf.stat.exists

- name: "set timezone to Asia/Tokyo"
  timezone: name=Asia/Tokyo