# /common_playbook/roles/httpd-for-zabbix/tasks

# Zabbixの使用に必要なパッケージ
- name: "install the latest version of httpd, php, php-bcmath, php-mbstring, php-gd, php-xml, php-mysqli"
  yum: name={{ item }} state=latest
  with_items:
    - httpd
    - php
    - php-bcmath
    - php-mbstring
    - php-gd
    - php-xml
    - php-mysqli

# Zabbixセットアップ時(Check of Pre-requisite)に求められる設定値に変更
- name: "edit max_execution_time of {{ php.ini }}"
  replace: dest="{{ php.ini }}" regexp='max_execution_time = .*$' replace="max_execution_time = {{ php.max_execution_time }}" backup=yes

- name: "edit max_input_time of {{ php.ini }}"
  replace: dest="{{ php.ini }}" regexp='max_input_time = .*$' replace="max_input_time = {{ php.max_input_time }}" backup=yes

- name: "edit post_max_size of {{ php.ini }}"
  replace: dest="{{ php.ini }}" regexp='post_max_size = .*$' replace="post_max_size = {{ php.post_max_size }}" backup=yes

- name: "edit date.timezone  of {{ php.ini }}"
  replace: dest="{{ php.ini }}" regexp=';date.timezone =$' replace="date.timezone = {{ php.timezone }}" backup=yes

- name: "start service httpd, if not running"
  service: name=httpd state=started enabled=yes