# /common_playbook/roles/zabbix-agent/defaults

zabbix:
  shortver: 3.2
  repo_url: http://repo.zabbix.com/zabbix/3.2/rhel/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/
  repo_key: https://repo.zabbix.com/zabbix-official-repo.key
  agentd_conf: /etc/zabbix/zabbix_agentd.conf
  server: 127.0.0.1